spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
---
Srping:
  application:
      name: package-web
---
info:
  name: package-web
  description: /swagger-ui.html
  version: 1.0
---
package: ####### 修改文件地址一定要把Resource实体中常量修改
  storageUrl: /img/
  storage: /C:/upload/package/img/file/
