spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

---
Srping:
  application:
      name: package-web
---
# mysql 数据连接信息
Spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:33006/hgl?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: Hgl2019@#$
#      url: jdbc:mysql://127.0.0.7:3306/package?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#      username: root
#      password: Xy#$%2020
  jpa:
    show-sql: true
---
info:
  name: package-web
  description: /swagger-ui.html
  version: 1.0
---
server:
  port: 9000
#  session:
# session失效时间，单位秒
#    timeout: 180

package:
  storage: D:\upload\package\file