spring:
  mvc:
    view:
      suffix: .html
      prefix: /
---
Srping:
  application:
      name: package-web
---
# mysql 数据连接信息
Spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/backage?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: root
  jpa:
    show-sql: true
---
info:
  name: package-web
  description: /swagger-ui.html
  version: 1.0
---
server:
  port: 9000
#  session:
# session失效时间，单位秒
#    timeout: 180

package:
  storage: D:\upload\package\file
